apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: {{ .Values.namespaces.data }}
  labels:
    app: {{ .Values.global.appName }}
    component: kafka
spec:
  type: {{ .Values.kafka.service.type }}
  ports:
    - name: external
      port: {{ .Values.kafka.service.port }}
      targetPort: 9092
    - name: plaintext
      port: 29092
      targetPort: 29092
    - name: controller
      port: 29093
      targetPort: 29093
  selector:
    app: {{ .Values.global.appName }}
    component: kafka

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: {{ .Values.namespaces.data }}
  labels:
    app: {{ .Values.global.appName }}
    component: kafka
spec:
  clusterIP: None
  selector:
    app: {{ .Values.global.appName }}
    component: kafka
  ports:
    - name: external
      port: 9092
      targetPort: 9092
    - name: plaintext
      port: 29092
      targetPort: 29092
    - name: controller
      port: 29093
      targetPort: 29093