apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: {{ .Values.global.namespaces.data }}
  labels:
    app: minio
spec:
  type: {{ .Values.minio.service.type }}
  selector:
    app: minio
  ports:
    - name: api
      port: {{ .Values.minio.service.ports.api }}
      targetPort: {{ .Values.minio.service.ports.api | default 9000 }}
    - name: console
      port: {{ .Values.minio.service.ports.console }}
      targetPort: {{ .Values.minio.service.ports.console | default 9001 }}
---
apiVersion: v1
kind: Service
metadata:
  name: minio-headless
  namespace: {{ .Values.global.namespaces.data }}
  labels:
    app: minio
spec:
  clusterIP: None
  selector:
    app: minio
  ports:
    - name: api
      port: {{ .Values.minio.service.ports.api }}
      targetPort: {{ .Values.minio.service.ports.api | default 9000 }}
    - name: console
      port: {{ .Values.minio.service.ports.console }}
      targetPort: {{ .Values.minio.service.ports.console | default 9001 }}
---
apiVersion: v1
kind: Service
metadata:
  name: minio-external
  namespace: {{ .Values.global.namespaces.data }}
  labels:
    app: minio
spec:
  type: LoadBalancer
  selector:
    app: minio
  ports:
    - name: api
      port: {{ .Values.minio.service.ports.api }}
      targetPort: {{ .Values.minio.service.ports.api | default 9000 }}
    - name: console
      port: {{ .Values.minio.service.ports.console }}
      targetPort: {{ .Values.minio.service.ports.console | default 9001 }}