trino:
  enabled: true
  coordinator:
    replicas: 1
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 1000m

  worker:
    replicas: 2
    resources:
      requests:
        memory: 2Gi
        cpu: 1000m
      limits:
        memory: 4Gi
        cpu: 2000m

  image:
    repository: phamviethoa2416/trino-realtime-lakehouse
    tag: v1.0.0
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    ports:
      http: 8080

  persistence:
    size: 5Gi
    storageClass: standard

  credentials:
    accessKey: minio-admin
    secretKey: minio-password