apiVersion: v1
kind: Service
metadata:
  name: starrocks-be-headless
  namespace: {{ .Values.namespaces.data }}
  labels:
    app: {{ .Values.global.appName }}
    component: starrocks-be
spec:
  clusterIP: None
  selector:
    app: {{ .Values.global.appName }}
    component: starrocks-be
  ports:
    - name: http
      port: {{ .Values.starrocks.backend.service.ports.http }}
      targetPort: {{ .Values.starrocks.backend.service.ports.http }}
    - name: rpc
      port: {{ .Values.starrocks.backend.service.ports.rpc }}
      targetPort: {{ .Values.starrocks.backend.service.ports.rpc }}
    - name: heartbeat
      port: {{ .Values.starrocks.backend.service.ports.heartbeat }}
      targetPort: {{ .Values.starrocks.backend.service.ports.heartbeat }}