apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: {{ .Values.global.namespaces.system }}
  labels:
    app: kafka
spec:
  clusterIP: None
  ports:
    - name: broker
      port: {{ .Values.kafka.service.ports.broker }}
      targetPort: {{ .Values.kafka.service.ports.broker }}
    - name: controller
      port: {{ .Values.kafka.service.ports.controller }}
      targetPort: {{ .Values.kafka.service.ports.controller }}
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka
spec:
  type: {{ .Values.kafka.service.type }}
  ports:
    - name: broker
      port: {{ .Values.kafka.service.ports.broker }}
      targetPort: {{ .Values.kafka.service.ports.broker }}
  selector:
    app: kafka