apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-coordinator
  namespace: {{ .Values.namespaces.data }}
  labels:
    app: {{ .Values.global.appName }}
    component: trino-coordinator
spec:
  replicas: {{ .Values.trino.coordinator.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.global.appName }}
      component: trino-coordinator
  template:
    metadata:
      labels:
        app: {{ .Values.global.appName }}
        component: trino-coordinator
    spec:
      containers:
        - name: trino-coordinator
          image: "{{ .Values.trino.image.repository}}:{{ .Values.trino.image.tag }}"
          imagePullPolicy: {{ .Values.trino.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.trino.service.ports.http }}
              name: http
          volumeMounts:
            - name: config
              mountPath: /etc/trino
              readOnly: true
          resources:
            {{ toYaml .Values.trino.coordinator.resources | nindent 12 }}
          env:
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: trino-secret
                  key: access-key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: trino-secret
                  key: secret-key
          readinessProbe:
            httpGet:
              path: /v1/info
              port: 8080
            initialDelaySeconds: {{ .Values.trino.probe.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.trino.probe.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.trino.probe.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.trino.probe.readiness.failureThreshold }}
          livenessProbe:
            httpGet:
              path: /v1/info
              port: 8080
            initialDelaySeconds: {{ .Values.trino.probe.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.trino.probe.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.trino.probe.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.trino.probe.liveness.failureThreshold }}
      volumes:
        - name: config
          configMap:
            name: trino-config
            items:
              - key: jvm.config
                path: jvm.config
              - key: log.properties
                path: log.properties
              - key: coordinator.properties
                path: config.properties
              - key: minio.properties
                path: catalog/iceberg.properties