global:
  appName: "streamhouse"
  networkPolicy:
    enabled: false

namespaces:
  system: "streamhouse-system"
  data: "streamhouse-data"
  monitoring: "streamhouse-monitoring"

kafka:
  enabled: true
  image:
    repository: apache/kafka
    tag: "4.0.0"
    pullPolicy: IfNotPresent
  replicas: 3
  persistence:
    enabled: true
    size: 5Gi
    storageClass: standard
  service:
    type: ClusterIP
    port: 9092
  config:
    numPartitions: 3
    replicationFactor: 3
    minInSyncReplicas: 2

#flink:
#  enabled: true
#  jobmanager:
#    replicas: 1
#    service:
#      type: ClusterIP
#      port: 8081
#  taskmanager:
#    replicas: 1
#    slots: 8
#  sqlClient:
#    enabled: true

minio:
  enabled: true
  image:
    repository: minio/minio
    tag: "RELEASE.2023-07-21T21-12-44Z"
    pullPolicy: IfNotPresent
  mode:
    type: distributed
    replicas: 4
  auth:
    rootUser: minio-admin
    rootPassword: minio-password
  persistence:
    enabled: true
    size: 5Gi
    storageClass: standard
  service:
    type: ClusterIP
    ports:
      api: 9000
      console: 9001
  config:
    region: ap-southeast-1
    browser: "on"
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}


#trino:
#  enabled: true
#  service:
#    type: NodePort
#    port: 8080
#  jvm:
#    maxMemory: 2G