apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-config
  namespace: {{ .Values.global.namespaces.system }}
  labels:
    app: flink
data:
  flink-conf.yaml: |
    cluster.id: flink-realtime-lakehouse

    jobmanager.rpc.address: flink-jobmanager
    jobmanager.rpc.port: 6123
    jobmanager.heap.size: 1536m
    taskmanager.heap.size: 4096m
    taskmanager.numberOfTaskSlots: 4

    high-availability: kubernetes
    high-availability.storageDir: s3a://flink-ha/metadata
    high-availability.cluster-id: flink-realtime-lakehouse
    kubernetes.cluster-id: flink-realtime-lakehouse
    kubernetes.namespace: {{ .Values.global.namespaces.system }}
    kubernetes.jobmanager.service-account: flink-service-account

    state.backend: rocksdb
    state.backend.incremental: true
    state.checkpoints.dir: s3://flink-checkpoints/
    state.savepoints.dir: s3://flink-savepoints/

    execution.checkpointing.interval: 60s
    execution.checkpointing.min-pause: 10s
    execution.checkpointing.timeout: 300s
    execution.checkpointing.max-concurrent-checkpoints: 1

    # Tuning cho RocksDB (tuỳ workload)
    state.backend.rocksdb.memory.managed: true
    state.backend.rocksdb.writebuffer.size: 64mb
    state.backend.rocksdb.writebuffer.count: 3
    state.backend.rocksdb.block-cache.size: 512mb
    state.backend.rocksdb.compaction.style: universal
    state.backend.rocksdb.thread.number: 4

    taskmanager.data.port: 6122
    taskmanager.rpc.port: 6120
    taskmanager.bind-host: 0.0.0.0

    taskmanager.network.memory.fraction: 0.1
    taskmanager.network.memory.min: 64mb
    taskmanager.network.memory.max: 1gb

    taskmanager.data.bind-port: 6122-6125

    rest.port: 8081
    jobmanager.web.submit.enable: true

    blob.server.port: 6124
    query.server.port: 6125
    parallelism.default: 4
    heartbeat.timeout: 10000
    heartbeat.interval: 5000

    s3.endpoint: http://minio.{{ .Values.global.namespaces.data }}.svc.cluster.local:9000
    s3.access-key: minio-admin
    s3.secret-key: minio-password
    s3.path-style-access: true

    fs.s3a.endpoint: http://minio.{{ .Values.global.namespaces.data }}.svc.cluster.local:9000
    fs.s3a.access.key: {{ .Values.flink.credentials.accessKey }}
    fs.s3a.secret.key: {{ .Values.flink.credentials.secretKey }}
    fs.s3a.path.style.access: true

  core-site.xml: |
    <configuration>
        <property>
            <name>fs.s3a.endpoint</name>
            <value>http://minio.{{ .Values.global.namespaces.data }}.svc.cluster.local:9000</value>
        </property>

        <property>
            <name>fs.s3a.access.key</name>
            <value>minio-admin</value>
        </property>

        <property>
            <name>fs.s3a.secret.key</name>
            <value>minio-password</value>
        </property>

        <property>
            <name>fs.s3a.path.style.access</name>
            <value>true</value>
        </property>
    </configuration>
