apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
  namespace: {{ .Values.global.namespaces.system }}
  labels:
    app: flink
    component: jobmanager
spec:
  type: {{ .Values.flink.jobmanager.service.type }}
  ports:
    - name: rpc
      port: {{ .Values.flink.jobmanager.service.ports.rpc }}
      targetPort: {{ .Values.flink.jobmanager.service.ports.rpc }}
    - name: blob
      port: {{ .Values.flink.jobmanager.service.ports.blob }}
      targetPort: {{ .Values.flink.jobmanager.service.ports.blob }}
    - name: query
      port: {{ .Values.flink.jobmanager.service.ports.query }}
      targetPort: {{ .Values.flink.jobmanager.service.ports.query }}
    - name: web
      port: {{ .Values.flink.jobmanager.service.ports.web }}
      targetPort: {{ .Values.flink.jobmanager.service.ports.web }}
  selector:
    app: flink
    component: jobmanager
---
apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager-headless
  namespace: {{ .Values.global.namespaces.system }}
  labels:
    app: flink
    component: jobmanager
spec:
  clusterIP: None
  ports:
    - name: rpc
      port: {{ .Values.flink.jobmanager.service.ports.rpc }}
      targetPort: {{ .Values.flink.jobmanager.service.ports.rpc }}
    - name: blob
      port: {{ .Values.flink.jobmanager.service.ports.blob }}
      targetPort: {{ .Values.flink.jobmanager.service.ports.blob }}
    - name: query
      port: {{ .Values.flink.jobmanager.service.ports.query }}
      targetPort: {{ .Values.flink.jobmanager.service.ports.query }}
    - name: web
      port: {{ .Values.flink.jobmanager.service.ports.web }}
      targetPort: {{ .Values.flink.jobmanager.service.ports.web }}
  selector:
    app: flink
    component: jobmanager