apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink-service-account
  namespace: {{ .Values.global.namespaces.system }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flink-role
  namespace: {{ .Values.global.namespaces.system }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "create", "patch", "update" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink-role-binding
  namespace: {{ .Values.global.namespaces.system }}
subjects:
  - kind: ServiceAccount
    name: flink-service-account
    namespace: {{ .Values.global.namespaces.system }}
roleRef:
  kind: Role
  name: flink-role
  apiGroup: rbac.authorization.k8s.io