apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: {{ .Values.namespaces.data }}
  labels:
    app: {{ .Values.global.appName }}
    component: postgresql
spec:
  type: {{ .Values.postgres.service.type }}
  selector:
      app: {{ .Values.global.appName }}
      component: postgresql
  ports:
    - name: postgresql
      port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-headless
  namespace: {{ .Values.namespaces.data }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.global.appName }}
    component: postgresql
  ports:
    - name: postgresql
      port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}