apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: streamhouse-data
  labels:
    app: {{ .Values.global.appName }}
    component: postgresql
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - name: postgresql
      port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}
  selector:
      app: {{ .Values.global.appName }}
      component: postgresql

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-headless
  namespace: streamhouse-data
spec:
  clusterIP: None
  selector:
    app: streamhouse
    component: postgresql
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432