apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trino-worker
  namespace: {{ .Values.global.namespaces.system }}
  labels:
    app: trino
    component: worker
spec:
  serviceName: trino-worker
  replicas: {{ .Values.trino.worker.replicas }}
  selector:
    matchLabels:
      app: trino
      component: worker
  template:
    metadata:
      labels:
        app: trino
        component: worker
    spec:
      containers:
        - name: trino-worker
          image: "{{ .Values.trino.image.repository}}:{{ .Values.trino.image.tag }}"
          imagePullPolicy: {{ .Values.trino.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.trino.service.ports.http }}
              name: http
          env:
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: trino-secret
                  key: access-key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: trino-secret
                  key: secret-key
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          startupProbe:
            httpGet:
              path: /v1/info
              port: {{ .Values.trino.service.ports.http }}
            periodSeconds: 5
            failureThreshold: 10
          readinessProbe:
            httpGet:
              port: {{ .Values.trino.service.ports.http }}
              path: /v1/info
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              port: {{ .Values.trino.service.ports.http }}
              path: /v1/info
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
          volumeMounts:
            - name: config
              mountPath: /etc/trino
              readOnly: true
            - name: data
              mountPath: /var/data/trino
          resources:
            {{ toYaml .Values.trino.worker.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: trino-config
            items:
              - key: jvm.config
                path: jvm.config
              - key: log.properties
                path: log.properties
              - key: worker.properties
                path: config.properties
              - key: worker.node.properties
                path: node.properties
              - key: paimon.properties
                path: catalog/paimon.properties
        - name: data
          emptyDir: {}