apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-worker
  namespace: {{ .Values.global.namespaces.system }}
  labels:
    app: trino
    role: worker
spec:
  replicas: {{ .Values.trino.worker.replicas }}
  selector:
    matchLabels:
      app: trino
      role: worker
  template:
    metadata:
      labels:
        app: trino
        role: worker
    spec:
      containers:
        - name: trino-worker
          image: "{{ .Values.trino.image.repository}}:{{ .Values.trino.image.tag }}"
          imagePullPolicy: {{ .Values.trino.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.trino.service.ports.http }}
              name: http
          env:
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: trino-secret
                  key: access-key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: trino-secret
                  key: secret-key
          readinessProbe:
            httpGet:
              port: {{ .Values.trino.service.ports.http }}
              path: /v1/info
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              port: {{ .Values.trino.service.ports.http }}
              path: /v1/info
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
          volumeMounts:
            - name: config
              mountPath: /etc/trino
              readOnly: true
          resources:
            {{ toYaml .Values.trino.worker.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: trino-config
            items:
              - key: jvm.config
                path: jvm.config
              - key: log.properties
                path: log.properties
              - key: worker.properties
                path: config.properties
              - key: node.properties
                path: node.properties
              - key: paimon.properties
                path: catalog/paimon.properties