minio:
  image:
    repository: minio/minio
    tag: latest
    pullPolicy: IfNotPresent

  mode:
    type: standalone
    replicas: 1

  auth:
    rootUser: minio-admin
    rootPassword: minio-password

  persistence:
    enabled: true
    size: 15Gi
    storageClass: standard

  service:
    type: ClusterIP
    ports:
      api: 9000
      console: 9001

  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m

  config:
    region: ap-southeast-1
    browser: "on"

  nodeSelector: {}
  tolerations: []
  affinity: {}