---
# Source: streamhouse/templates/minio/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: streamhouse-data
type: Opaque
data:
  rootUser: "bWluaW8tYWRtaW4="
  rootPassword: "bWluaW8tcGFzc3dvcmQ="
  accessKey: "bWluaW8tYWRtaW4="
  secretKey: "bWluaW8tcGFzc3dvcmQ="
  region: "YXAtc291dGhlYXN0LTE="
---
# Source: streamhouse/templates/minio/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: minio-headless
  namespace: streamhouse-data
  labels:
    app: streamhouse
    component: minio
spec:
  clusterIP: None
  selector:
    app: streamhouse
    component: minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
---
# Source: streamhouse/templates/minio/deployment.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: streamhouse-data
  labels:
    app: streamhouse
    component: minio
spec:
  serviceName: minio-headless
  replicas: 4
  selector:
    matchLabels:
      app: streamhouse
      component: minio
  template:
    metadata:
      labels:
        app: streamhouse
        component: minio
    spec:
      containers:
        - name: minio
          image: "minio/minio:RELEASE.2023-10-02T23-00-00Z"
          imagePullPolicy: IfNotPresent
          args:
            - server
            - http://minio-0.minio-headless.streamhouse-data.svc.cluster.local/data
            - http://minio-1.minio-headless.streamhouse-data.svc.cluster.local/data
            - http://minio-2.minio-headless.streamhouse-data.svc.cluster.local/data
            - http://minio-3.minio-headless.streamhouse-data.svc.cluster.local/data
            - --console-address
            - ":9001"
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: rootUser
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: rootPassword
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: accessKey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: secretKey
            - name: MINIO_REGION_NAME
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: region
          ports:
            - containerPort: 9000
              name: api
            - containerPort: 9001
              name: console
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 10
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: 5Gi
