---
# Source: streamhouse/templates/trino/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: trino-secret
  namespace: streamhouse-data
  labels:
    app: streamhouse
    component: trino
type: Opaque
data:
  access-key: "bWluaW8tYWRtaW4="
  secret-key: "bWluaW8tcGFzc3dvcmQ="
---
# Source: streamhouse/templates/trino/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-config
  namespace: streamhouse-data
  labels:
    app: streamhouse
    component: trino
data:
  jvm.config: |
    -Xmx2G
    -XX:+ExitOnOutOfMemoryError
    -XX:+UseG1GC
    -XX:+UseStringDeduplication
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:HeapDumpPath=/tmp
  log.properties: |
    io.trino=INFO
    io.trino.plugin.jdbc=DEBUG
    io.trino.plugin.hive=DEBUG
    io.trino.plugin.iceberg=DEBUG

  coordinator.properties: |
    coordinator=true
    node-scheduler.include-coordinator=false
    node.environment=production
    http-server.http.port=8080
    query.max-memory=5GB
    query.max-memory-per-node=1GB
    discovery.uri=http://trino:8080

    fs.native-s3.enabled=true
    s3.endpoint=http://minio:9000
    s3.region=ap-southeast-1
    s3.path-style-access=true
    s3.ssl.enabled=false
    s3.access-key=${S3_ACCESS_KEY}
    s3.secret-key=${S3_SECRET_KEY}

  worker.properties: |
    coordinator=false
    http-server.http.port=8080
    node.environment=production
    query.max-memory=5GB
    query.max-memory-per-node=1GB
    discovery.uri=http://trino:8080

    fs.native-s3.enabled=true
    s3.endpoint=http://minio:9000
    s3.region=ap-southeast-1
    s3.path-style-access=true
    s3.ssl.enabled=false
    s3.access-key=${S3_ACCESS_KEY}
    s3.secret-key=${S3_SECRET_KEY}

  minio.properties: |
    connector.name=iceberg
    iceberg.catalog.type=rest
    iceberg.rest-catalog.uri=http://polaris:8181
    iceberg.rest-catalog.warehouse=s3a://warehouse
    iceberg.file-format=parquet
---
# Source: streamhouse/templates/trino/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: trino
  namespace: streamhouse-data
  labels:
    app: streamhouse
    component: trino-coordinator
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: streamhouse
    component: trino-coordinator
---
# Source: streamhouse/templates/trino/coordinator-statefulset.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-coordinator
  namespace: streamhouse-data
  labels:
    app: streamhouse
    component: trino-coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamhouse
      component: trino-coordinator
  template:
    metadata:
      labels:
        app: streamhouse
        component: trino-coordinator
    spec:
      containers:
        - name: trino-coordinator
          image: "trinodb/trino:475"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: config
              mountPath: /etc/trino
              readOnly: true
          resources:
            
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          env:
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: trino-secret
                  key: access-key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: trino-secret
                  key: secret-key
          readinessProbe:
            httpGet:
              path: /v1/info
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /v1/info
              port: 8080
            initialDelaySeconds: 300
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
      volumes:
        - name: config
          configMap:
            name: trino-config
            items:
              - key: jvm.config
                path: jvm.config
              - key: log.properties
                path: log.properties
              - key: coordinator.properties
                path: config.properties
              - key: minio.properties
                path: catalog/iceberg.properties
---
# Source: streamhouse/templates/trino/worker-statefulset.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-worker
  namespace: streamhouse-data
  labels:
      app: streamhouse
      component: trino-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: streamhouse
      component: trino-worker
  template:
    metadata:
      labels:
        app: streamhouse
        component: trino-worker
    spec:
      containers:
        - name: trino-worker
          image: "trinodb/trino:475"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: trino-secret
                  key: access-key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: trino-secret
                  key: secret-key
          readinessProbe:
            httpGet:
              path: /v1/info
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /v1/info
              port: 8080
            initialDelaySeconds: 300
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: config
              mountPath: /etc/trino
              readOnly: true
          resources:
            
            limits:
              cpu: 2000m
              memory: 4Gi
            requests:
              cpu: 1000m
              memory: 2Gi
      volumes:
        - name: config
          configMap:
            name: trino-config
            items:
              - key: jvm.config
                path: jvm.config
              - key: log.properties
                path: log.properties
              - key: worker.properties
                path: config.properties
              - key: minio.properties
                path: catalog/iceberg.properties
